### ISSUE TITLE
I do not quite understand the last task 'Add "Send your message" form

### ISSUE THREAD

**Issue by nurlanotek** [xbaysal11/com-front#12]
I do not quite understand the last task 'Add "Send your message" form, so users can auto send messages from the page'. Should there be a pop-up messenger, like the one Intercom service provides? Where should messages end up after the user would send them? Should there be an SMTP server to send those messages to the administration email?

![image](https://user-images.githubusercontent.com/793168/66718468-2507e680-ee06-11e9-8e50-cc30c7245ccb.png)

_Originally posted by @IslaMurtazaev in https://github.com/xbaysal11/com-front/issues/5#issuecomment-541423612_

**Comment by xbaysal11** [comment]
I finished the task but the github does not allow us to use the php code in the github page
http://xbaysal11.ml/xbaysal11-b6bnTdA.png
@nurlanotek
