### ISSUE TITLE
Admission link from Nav Bar

### ISSUE THREAD

**Issue by nurlanotek** [xbaysal11/com-front#14]
- [x] Admission on Bachelor program link it to the [Admission page](http://alatoo.edu.kg/view/public/pages/page.xhtml?id=66) of AIU
- [x] Admission on Master program link it to the [Admission page](http://alatoo.edu.kg/view/public/pages/page.xhtml?id=197) of AIU

@NasipCOM

**Comment by AIDARXAN** [comment]
@nurlanotek кто нибудь сделайте это

**Comment by IslaMurtazaev** [comment]
I will fix it @NasipCOM
