### ISSUE TITLE
Academic Calendar <- Calendar

### ISSUE THREAD

**Issue by nurlanotek** [xbaysal11/com-front#15]
- [x] The Academic Calendar link inside calendar menu must be linked to the AIU's Academic [calendar page](http://alatoo.edu.kg/view/public/pages/page.xhtml?id=281).
- [x] The "Academic Calendar" of AIU must be opened inside new TAB.

@NasipCOM

**Comment by AIDARXAN** [comment]
https://github.com/xbaysal11/com-front/commit/989f2cd6e1d13ad47216e7e68a51661fc2e0006c

commit that solved problem
