### ISSUE TITLE
Flaw on the home page image

### ISSUE THREAD

**Issue by AIDARXAN** [xbaysal11/com-front#2]
On the home, where is the image of our university one of the angles is cut
![Selection_011](https://user-images.githubusercontent.com/32789734/64754975-40ec4400-d54b-11e9-834e-8cd8ec84f737.png)

**Comment by xbaysal11** [comment]
> On the home, where is the image of our university one of the angles is cut
> ![Selection_011](https://user-images.githubusercontent.com/32789734/64754975-40ec4400-d54b-11e9-834e-8cd8ec84f737.png)

@AIDARXAN Can you paint me better please?

**Comment by AIDARXAN** [comment]
@xbaysal11 
![Selection_013](https://user-images.githubusercontent.com/32789734/64857718-28615400-d647-11e9-9508-29629f31ac54.png)
