### ISSUE TITLE
Contacts page info outdated

### ISSUE THREAD

**Issue by nurlanotek** [xbaysal11/com-front#5]
- [x] The name of the university is not correct.
- [x] Add Google Map or something similar.
- [x] Add mobile icon in front of mobile phone contacts
- [x] Add address icon in front of the address
- [x] Remove University email address from the page
- [x] Add "Send your message" form, so users can auto send messages from the page
- [x] Change Background image on Contacts page
- [x] Remove "Lab Contacts" text from the banner image.
@NasipCOM

**Comment by AIDARXAN** [comment]
@nurlanotek why google map, 2 gis is good too?

**Comment by AIDARXAN** [comment]
@nurlanotek because google maps is need payment after 5k visits to the site, but 2gis not

**Comment by AIDARXAN** [comment]
@nurlanotek because google maps is need payment after 5k visits to the site but without it there will be ugly watermark and , but 2gis not

**Comment by IslaMurtazaev** [comment]
I do not quite understand the last task 'Add "Send your message" form, so users can auto send messages from the page'. Should there be a pop-up messenger, like the one Intercom service provides? Where should messages end up after the user would send them? Should there be an SMTP server to send those messages to the administration email?

**Comment by IslaMurtazaev** [comment]
> @nurlanotek because google maps is need payment after 5k visits to the site but without it there will be ugly watermark and , but 2gis not

**Comment by IslaMurtazaev** [comment]
Let's open a new issue for the remaining task, with more description.
