### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by nurlanotek** [xbaysal11/com-front#7]
- [x] Remove **bubbles** from the front page
- [ ] Schedule of Lectures page is not working. Schedule is not displayed.
- [x] What is "Computer Science" text includes the wrong "department" name. Fix it.

@NasipCOM

**Comment by xbaysal11** [comment]
> * What is "Computer Science" text includes the wrong "department" name. Fix it.
 Can you explain what do you mean ?(What is "Computer Science" text includes the wrong "department" name. Fix it.)
Preferably with screenshot
@nurlanotek

**Comment by xbaysal11** [comment]
> * Schedule of Lectures page is not working. Schedule is not displayed.

We don't have permission to use schedule doc in our website.
https://prnt.sc/pgbxt1
@nurlanotek

**Comment by NasipCOM** [comment]
What is "Computer Science" text includes the wrong "department" name. Fix it.
Can you explain what do you mean ?(What is "Computer Science" text includes the wrong "department" name. Fix it.)

That was in department / Info, I already fixed it.

**Comment by xbaysal11** [comment]
> What is "Computer Science" text includes the wrong "department" name. Fix it.
> Can you explain what do you mean ?(What is "Computer Science" text includes the wrong "department" name. Fix it.)
> 
> That was in department / Info, I already fixed it.

Ok, thank you.
